[package]
name = "vaults"
version = "mainnet-v1.33.0"
edition = "2024"
published-at = "0x9eeac6aa7bd9059fb61b26d031152c2d9e87f120f391aa58b54f4d23e7f52d05"

[dependencies.pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-mainnet"

[dependencies.pyth_pro_compatible]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-pro-compatible-contract-mainnet"
rename-from = "pyth"

[dependencies]
farming = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/stable_farming", rev = "mainnet-v1.52.3" }
cetus_clmm = { r.mvr = "@cetuspackages/clmm" }
move_stl = { r.mvr = "@cetuspackages/move-stl" }
integer_mate = { r.mvr = "@cetuspackages/inter-mate" }
