[package]
name = "vaults"
version = "1.2.0"

[dependencies]
farming = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/stable_farming", rev = "mainnet-v1.52.3" }
cetus_clmm = { r.mvr = "@cetuspackages/clmm" }
move_stl = { r.mvr = "@cetuspackages/move-stl" }
integer_mate = { r.mvr = "@cetuspackages/inter-mate" }
