[package]
name = "xcetus"
version = "1.0.0"

[dependencies]
move_stl = { r.mvr = "@cetuspackages/move-stl" }
cetus = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/token/cetus", rev = "mainnet-v1.48.2" }
