[package]
name = "clmm_vester"
edition = "2024.beta"

[dependencies]
integer_mate = { r.mvr = "@cetuspackages/inter-mate" }
cetus = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/token/cetus", rev = "mainnet-v1.48.2", override = true }
cetus_clmm = { r.mvr = "@cetuspackages/clmm" }
