[package]
name = "lpburn"
version = "1.2.0"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
clmm_vester = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/clmm_vester", rev = "mainnet-v1.52.0" }
cetus_clmm = { r.mvr = "@cetuspackages/clmm" }
integer_mate = { r.mvr = "@cetuspackages/inter-mate" }
cetus = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/token/cetus", rev = "mainnet-v1.48.2" }
