[package]
name = "dividends"
version = "1.0.3"

[dependencies]
move_stl = { r.mvr = "@cetuspackages/move-stl", override = true }
xcetus = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/token/xcetus", rev = "mainnet-v1.48.2" }
